# Generated by Django 2.2 on 2020-03-10 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='monitor.Site_User')),
                ('to_user_msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='monitor.Site_User')),
            ],
        ),
    ]
