# Generated by Django 2.2 on 2019-12-14 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_user_userskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('group_size', models.IntegerField(blank=True, null=True)),
                ('estimated_work_duration', models.IntegerField(blank=True, null=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='monitor.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isTeacher', models.BooleanField(default=False)),
                ('isLearner', models.BooleanField(default=True)),
                ('start_at', models.DateField(null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.User')),
            ],
        ),
        migrations.CreateModel(
            name='GroupNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(null=True)),
                ('priority', models.CharField(choices=[('LW', 'LOW'), ('MD', 'MEDIUM'), ('HG', 'HIGH')], default='LW', max_length=2)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Group')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='monitor.Notification')),
            ],
        ),
    ]
